name: Deploy to Vercel Staging
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_ncO5HTtbe2jC18C7NAs5WiryuN0M/q9lErPKtHz"
